"""The awaitable spellings of tors's large-input functions (see
``tors/aio.py`` for which functions and why only these). Signatures
mirror ``__init__.pyi`` exactly, ``async def`` in place of ``def`` and
the bare resolved type in place of the return annotation (an
``async def`` function's annotation is what awaiting it resolves to,
not ``Awaitable[T]``, which describes the coroutine object itself,
not its result). This stub is generated by ``tools/gen_aio_stub.py``
and checked against the sync stub by ``tests/test_aio.py``.
"""

from typing import Literal

from tors import CompiledLemmaDict, _StemmerLanguage

async def diff_opcodes(
    a: str, b: str, *, deadline_ms: float | None = None
) -> list[tuple[str, int, int, int, int]]: ...


async def diff_opcodes_lines(
    a: str, b: str, *, deadline_ms: float | None = None
) -> list[tuple[str, int, int, int, int]]: ...


async def chunk_cdc(
    data: bytes, *, min_size: int = 4096, avg_size: int = 16384, max_size: int = 65534
) -> list[tuple[int, int]]: ...


async def chunk_text(
    text: str,
    max_chars: int,
    *,
    overlap: int = 0,
    boundary: Literal["word", "sentence"] = "word",
) -> list[tuple[int, int]]: ...


async def chunk_by_words(
    text: str, words_per_chunk: int, *, overlap: int = 0
) -> list[tuple[int, int]]: ...


async def chunk_by_sentences(
    text: str, sentences_per_chunk: int, *, overlap: int = 0
) -> list[tuple[int, int]]: ...


async def chunk_by_paragraphs(
    text: str, paragraphs_per_chunk: int, *, overlap: int = 0
) -> list[tuple[int, int]]: ...


async def chunk_hierarchical(
    text: str,
    max_chars: int,
    separators: list[str] | None = None,
    *,
    overlap: int = 0,
) -> list[tuple[int, int]]: ...


async def tf_idf(
    corpus: list[str],
    *,
    strip_accents: bool = False,
    stemmer: _StemmerLanguage | None = None,
    lemma_dict: dict[str, str] | CompiledLemmaDict | None = None,
) -> list[list[tuple[str, float]]]: ...


async def bm25_rank(
    query: str,
    corpus: list[str],
    *,
    k1: float = 1.5,
    b: float = 0.75,
    strip_accents: bool = False,
    stemmer: _StemmerLanguage | None = None,
    lemma_dict: dict[str, str] | CompiledLemmaDict | None = None,
) -> list[tuple[int, float]]: ...


async def apply_pipeline(
    texts: list[str],
    *,
    nfd: bool = False,
    lowercase: bool = False,
    strip_accents: bool = False,
    stemmer: _StemmerLanguage | None = None,
    lemma_dict: dict[str, str] | CompiledLemmaDict | None = None,
    collapse_whitespace: bool = False,
) -> list[str]: ...
