"""The awaitable spellings of tors's large-input functions (see
``tors/aio.py`` for which functions and why only these). Signatures
mirror ``__init__.pyi`` exactly, ``async def`` in place of ``def`` and
the bare resolved type in place of the return annotation (an
``async def`` function's annotation is what awaiting it resolves to,
not ``Awaitable[T]``, which describes the coroutine object itself,
not its result). This stub is generated by ``tools/gen_aio_stub.py``
and checked against the sync stub by ``tests/test_aio.py``.
"""

from collections.abc import Callable, Hashable, Sequence
from typing import Any, Literal

from tors import (
    CompiledLemmaDict,
    DedupResult,
    GroundingResult,
    RepairAction,
    ScrubPiiReport,
    SentenceGrounding,
    StemmerLanguage,
)

async def normalize(text: str) -> str: ...
async def finalize(text: str) -> tuple[str, str]: ...
async def strip_controls(text: str) -> str: ...
async def scrub_pii(
    text: str,
    rules: Sequence[Literal["contact_email", "contact_phone", "api_keys"]] | None = None,
    *,
    salt: str | None = None,
    families: Sequence[str] | None = None,
) -> str: ...
async def scrub_pii_report(
    text: str,
    rules: Sequence[Literal["contact_email", "contact_phone", "api_keys"]] | None = None,
    *,
    salt: str | None = None,
    families: Sequence[str] | None = None,
) -> ScrubPiiReport: ...
async def scrub_log_text(
    text: str,
    rules: Sequence[
        Literal["pg_detail_lines", "uri_userinfo", "uri_query_creds", "libpq_conninfo_creds"]
    ]
    | None = None,
) -> str: ...
async def word_bounds(text: str) -> list[tuple[int, int]]: ...
async def sentence_bounds(text: str) -> list[tuple[int, int]]: ...
async def decode_utf8(raw: bytes, *, errors: Literal["strict", "replace"] = "strict") -> str: ...
async def finalize_utf8(
    raw: bytes, *, errors: Literal["strict", "replace"] = "strict"
) -> tuple[str, str]: ...
async def b64_encode_bytes(raw: bytes) -> str: ...
async def b64_decode(s: str, *, validate: bool = True) -> bytes: ...
async def decode_utf16(
    raw: bytes,
    *,
    errors: Literal["strict", "replace"] = "strict",
    byteorder: Literal["native", "little", "big"] = "native",
) -> str: ...
async def diff_opcodes(
    a: str, b: str, *, deadline_ms: float | None = None
) -> list[tuple[str, int, int, int, int]]: ...
async def diff_opcodes_lines(
    a: str, b: str, *, deadline_ms: float | None = None
) -> list[tuple[str, int, int, int, int]]: ...
async def replace_many(text: str, replacements: dict[str, str]) -> str: ...
async def find_patterns(patterns: list[str], text: str) -> list[tuple[int, int, int]]: ...
async def count_matches(patterns: list[str], text: str) -> int: ...
async def extract_code_blocks(
    text: str, lang: str | None = None
) -> list[tuple[str | None, str, int, int]]: ...
async def strip_code_fences(text: str) -> str: ...
async def repair_json(
    s: str,
    *,
    skip_json_loads: bool = False,
    ensure_ascii: bool = True,
    strict: bool = False,
    # a pydantic v2 model (class or instance) is also accepted
    schema: dict[str, Any] | bool | type[Any] | None = None,
    salvage: bool = False,
    locale: str | dict[str, str] | None = None,
    deadline_ms: float | None = None,
) -> str: ...
async def repair_json_loads(
    s: str,
    *,
    skip_json_loads: bool = False,
    strict: bool = False,
    # a pydantic v2 model (class or instance) is also accepted
    schema: dict[str, Any] | bool | type[Any] | None = None,
    salvage: bool = False,
    locale: str | dict[str, str] | None = None,
    deadline_ms: float | None = None,
) -> dict[str, Any] | list[Any] | str | int | float | bool | None: ...
async def repair_json_diagnostics(
    s: str,
    *,
    skip_json_loads: bool = False,
    strict: bool = False,
    # a pydantic v2 model (class or instance) is also accepted
    schema: dict[str, Any] | bool | type[Any] | None = None,
    salvage: bool = False,
    locale: str | dict[str, str] | None = None,
    deadline_ms: float | None = None,
) -> tuple[
    dict[str, Any] | list[Any] | str | int | float | bool | None,
    list[RepairAction],
]: ...
async def truncate_to_bounds(
    text: str, max_chars: int, boundary: Literal["word", "sentence"] = "word"
) -> str: ...
async def truncate_ellipsis(text: str, max_chars: int) -> str: ...
async def is_grounded(
    claim: str,
    source: str,
    *,
    fuzzy: bool = False,
    threshold: float = 0.85,
    deadline_ms: float | None = None,
) -> bool: ...
async def grounding_coverage(source: str, text: str) -> float: ...
async def highlight(
    query: str,
    text: str,
    *,
    max_snippets: int = 3,
    max_chars: int = 400,
) -> GroundingResult: ...
async def ground_sentences(
    text: str,
    query: str,
    *,
    max_chars: int | None = None,
) -> SentenceGrounding: ...
async def similarity_ratio(a: str, b: str, *, deadline_ms: float | None = None) -> float: ...
async def get_close_matches(
    word: str,
    possibilities: list[str],
    n: int = 3,
    cutoff: float = 0.6,
    *,
    deadline_ms: float | None = None,
) -> list[str]: ...
async def levenshtein(a: str, b: str, *, deadline_ms: float | None = None) -> int: ...
async def jaro(a: str, b: str, *, deadline_ms: float | None = None) -> float: ...
async def jaro_winkler(a: str, b: str, *, deadline_ms: float | None = None) -> float: ...
async def replace_many_masked(text: str, replacements: dict[str, str], mask: str = "*") -> str: ...
async def chunk_cdc(
    data: bytes, *, min_size: int = 4096, avg_size: int = 16384, max_size: int = 65534
) -> list[tuple[int, int]]: ...
async def chunk_text(
    text: str,
    max_chars: int,
    *,
    overlap: int = 0,
    boundary: Literal["word", "sentence"] = "word",
) -> list[tuple[int, int]]: ...
async def chunk_by_words(
    text: str, words_per_chunk: int, *, overlap: int = 0
) -> list[tuple[int, int]]: ...
async def chunk_by_sentences(
    text: str, sentences_per_chunk: int, *, overlap: int = 0
) -> list[tuple[int, int]]: ...
async def chunk_by_paragraphs(
    text: str, paragraphs_per_chunk: int, *, overlap: int = 0
) -> list[tuple[int, int]]: ...
async def chunk_by_lines(
    text: str, lines_per_chunk: int, *, overlap: int = 0
) -> list[tuple[int, int]]: ...
async def chunk_hierarchical(
    text: str,
    max_chars: int,
    separators: Sequence[str | None] | None = None,
    *,
    overlap: int = 0,
    overlap_boundary: Literal["grapheme", "word"] = "grapheme",
) -> list[tuple[int, int]]: ...
async def chunk_to_budget(
    text: str,
    token_counter: Callable[[str], int],
    *,
    max_tokens: int,
    overlap: int | float = 0,
) -> list[tuple[int, int]]: ...
async def chunk_to_offsets(
    text: str,
    token_offsets: Sequence[tuple[int, int]],
    *,
    max_tokens: int,
    overlap: int | float = 0,
) -> list[tuple[int, int]]: ...
async def minhash_signature(
    text: str,
    *,
    num_perm: int = 128,
    shingle_size: int = 3,
    seed: int = 0,
) -> list[int]: ...
async def shingle_jaccard(a: str, b: str, *, width: int = 3) -> float: ...
async def shingle_dice(a: str, b: str, *, width: int = 3) -> float: ...
async def dedup_near_dup(
    texts: list[str],
    *,
    threshold: float = 0.9,
    method: Literal["simhash", "shingle", "minhash"] = "simhash",
) -> DedupResult: ...
async def tf_idf(
    corpus: list[str],
    *,
    strip_accents: bool = False,
    stemmer: StemmerLanguage | None = None,
    lemma_dict: dict[str, str] | CompiledLemmaDict | None = None,
) -> list[list[tuple[str, float]]]: ...
async def bm25_rank(
    query: str,
    corpus: list[str],
    *,
    k1: float = 1.5,
    b: float = 0.75,
    strip_accents: bool = False,
    stemmer: StemmerLanguage | None = None,
    lemma_dict: dict[str, str] | CompiledLemmaDict | None = None,
) -> list[tuple[int, float]]: ...
async def rank_fuse(
    ranked_lists: list[list[Hashable]], *, k: int = 60
) -> list[tuple[Hashable, float]]: ...
async def ndcg_at_k(
    ranked: list[Hashable],
    relevant: set[Hashable] | frozenset[Hashable],
    *,
    k: int | None = None,
    gains: dict[Hashable, float] | None = None,
) -> float: ...
async def mrr(
    ranked: list[Hashable],
    relevant: set[Hashable] | frozenset[Hashable],
) -> float: ...
async def recall_at_k(
    ranked: list[Hashable],
    relevant: set[Hashable] | frozenset[Hashable],
    k: int,
) -> float: ...
async def precision_at_k(
    ranked: list[Hashable],
    relevant: set[Hashable] | frozenset[Hashable],
    k: int,
) -> float: ...
async def apply_pipeline(
    texts: list[str],
    *,
    nfd: bool = False,
    lowercase: bool = False,
    strip_accents: bool = False,
    stemmer: StemmerLanguage | None = None,
    lemma_dict: dict[str, str] | CompiledLemmaDict | None = None,
    collapse_whitespace: bool = False,
) -> list[str]: ...
