"""Regenerate ``python/tors/aio.pyi`` from ``python/tors/__init__.pyi``.

The async facade's signatures are the sync signatures with ``async def``
in place of ``def`` and the SAME return annotation (an ``async def``
function's annotation is what awaiting it resolves to, not
``Awaitable[T]`` — that describes the coroutine object itself, not its
result); deriving the stub from the sync stub keeps the two from
drifting apart, and ``tests/test_aio.py`` fails loudly if the committed
artifact is stale (regenerate with this script as part of the same
change that touches the sync stub).

Only the curated large-input functions named in ``tors.aio._WRAPPED``
are translated (see ``tors/aio.py``'s module docstring for why the rest
of ``tors`` intentionally has no async twin — most functions are cheap
enough that a thread hop would cost more than the call itself). The sync
stub's comments travel with their functions so the GIL notes stay
readable in both spellings.
"""

from __future__ import annotations

import ast
from pathlib import Path

SYNC_STUB = Path(__file__).resolve().parent.parent / "python" / "tors" / "__init__.pyi"
ASYNC_STUB = Path(__file__).resolve().parent.parent / "python" / "tors" / "aio.pyi"


def _translate(source: str, wrapped: frozenset[str]) -> tuple[str, int]:
    tree = ast.parse(source)
    lines = source.split("\n")
    header = [
        '"""The awaitable spellings of tors\'s large-input functions (see',
        "``tors/aio.py`` for which functions and why only these). Signatures",
        "mirror ``__init__.pyi`` exactly, ``async def`` in place of ``def`` and",
        "the bare resolved type in place of the return annotation (an",
        '``async def`` function\'s annotation is what awaiting it resolves to,',
        "not ``Awaitable[T]``, which describes the coroutine object itself,",
        "not its result). This stub is generated by ``tools/gen_aio_stub.py``",
        "and checked against the sync stub by ``tests/test_aio.py``.",
        '"""',
        "",
        "from typing import Literal",
        "",
        "from tors import CompiledLemmaDict, _StemmerLanguage",
        "",
    ]
    out: list[str] = header
    translated = 0
    for node in tree.body:
        if not isinstance(node, ast.FunctionDef) or node.name not in wrapped:
            continue
        chunk = "\n".join(lines[node.lineno - 1 : node.end_lineno]).rstrip()
        chunk = chunk.replace(f"def {node.name}(", f"async def {node.name}(", 1)
        out.append(chunk)
        out.append("")
        out.append("")
        translated += 1
    return "\n".join(out).rstrip("\n") + "\n", translated


def main() -> None:
    from tors.aio import _WRAPPED

    source = SYNC_STUB.read_text(encoding="utf-8")
    text, count = _translate(source, frozenset(_WRAPPED))
    ASYNC_STUB.write_text(text, encoding="utf-8")
    print(f"written {ASYNC_STUB}: {count} async signatures")


if __name__ == "__main__":
    main()
