"""Regenerate ``python/tors/aio.pyi`` from ``python/tors/__init__.pyi``.

The async facade's signatures are the sync signatures with ``async def``
in place of ``def`` and the SAME return annotation (an ``async def``
function's annotation is what awaiting it resolves to, not
``Awaitable[T]`` — that describes the coroutine object itself, not its
result); deriving the stub from the sync stub keeps the two from
drifting apart, and ``tests/test_aio.py`` fails loudly if the committed
artifact is stale (regenerate with this script as part of the same
change that touches the sync stub).

Only the curated large-input functions named in ``tors.aio._WRAPPED``
are translated (see ``tors/aio.py``'s module docstring for why the rest
of ``tors`` intentionally has no async twin — most functions are cheap
enough that a thread hop would cost more than the call itself). Only the
SIGNATURES travel: the extraction is each function's ``def`` lines
(``lines[node.lineno - 1 : node.end_lineno]``), so the sync stub's
comments stay in the sync stub and the generated ``aio.pyi`` carries no
comments at all.

The translated text is piped through ``ruff format`` (the repo's
formatter, a dev-group dependency, invoked as ``python -m ruff``)
before it is returned or written: the emitted artifact is
ruff-format-clean BY CONSTRUCTION, so the committed stub, the
generator, and the formatter can never disagree about style — the
freshness gate in ``tests/test_aio.py`` compares this function's output
against the committed file, and both sides are the formatted spelling.
"""

from __future__ import annotations

import ast
import subprocess
import sys
from pathlib import Path

SYNC_STUB = Path(__file__).resolve().parent.parent / "python" / "tors" / "__init__.pyi"
ASYNC_STUB = Path(__file__).resolve().parent.parent / "python" / "tors" / "aio.pyi"


def _ruff_format(text: str) -> str:
    """Run ``ruff format`` over ``text`` as if it were ``aio.pyi``.

    ``--stdin-filename`` makes ruff apply the ``.pyi`` spacing rules (zero
    blank lines between top-level defs) and the project's ``pyproject.toml``
    config, so the output is exactly what formatting the committed file in
    place would produce. Raises ``RuntimeError`` rather than emitting an
    unformatted stub if ruff is missing or refuses the input — a stale or
    malformed artifact must never be written silently.
    """
    # Fixed argv, no shell, the repo's own formatter.
    proc = subprocess.run(
        [sys.executable, "-m", "ruff", "format", "--stdin-filename", str(ASYNC_STUB), "-"],
        input=text,
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"ruff format failed (rc={proc.returncode}) while generating {ASYNC_STUB}: "
            f"{proc.stderr.strip()}"
        )
    return proc.stdout


def _translate(source: str, wrapped: frozenset[str]) -> tuple[str, int]:
    tree = ast.parse(source)
    lines = source.split("\n")
    header = [
        '"""The awaitable spellings of tors\'s large-input functions (see',
        "``tors/aio.py`` for which functions and why only these). Signatures",
        "mirror ``__init__.pyi`` exactly, ``async def`` in place of ``def`` and",
        "the bare resolved type in place of the return annotation (an",
        "``async def`` function's annotation is what awaiting it resolves to,",
        "not ``Awaitable[T]``, which describes the coroutine object itself,",
        "not its result). This stub is generated by ``tools/gen_aio_stub.py``",
        "and checked against the sync stub by ``tests/test_aio.py``.",
        '"""',
        "",
        "from collections.abc import Sequence",
        "from typing import Literal",
        "",
        "from tors import CompiledLemmaDict, _StemmerLanguage",
        "",
    ]
    out: list[str] = header
    translated = 0
    for node in tree.body:
        if not isinstance(node, ast.FunctionDef) or node.name not in wrapped:
            continue
        chunk = "\n".join(lines[node.lineno - 1 : node.end_lineno]).rstrip()
        chunk = chunk.replace(f"def {node.name}(", f"async def {node.name}(", 1)
        out.append(chunk)
        out.append("")
        out.append("")
        translated += 1
    raw = "\n".join(out).rstrip("\n") + "\n"
    return _ruff_format(raw), translated


def main() -> None:
    from tors.aio import _WRAPPED

    source = SYNC_STUB.read_text(encoding="utf-8")
    text, count = _translate(source, frozenset(_WRAPPED))
    ASYNC_STUB.write_text(text, encoding="utf-8")
    print(f"written {ASYNC_STUB}: {count} async signatures")


if __name__ == "__main__":
    main()
